version: '3.8'

services:
  azure-diagram-mcp:
    build: .
    image: azure-diagram-mcp:latest
    container_name: azure-diagram-mcp-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Azure OpenAI configuration (optional)
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT:-gpt-4}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-08-01-preview}
    volumes:
      # Mount output directory for generated diagrams
      - ./output:/app/output
      # Mount current directory for development (optional)
      - .:/app/workspace:ro
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import azure_diagram_server; print('Server healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge

volumes:
  diagram_output:
    driver: local
